ok

diff --git a/docker/php/Dockerfile b/docker/php/Dockerfile
--- a/docker/php/Dockerfile
+++ b/docker/php/Dockerfile
@@ -1,49 +1,115 @@
+# From
 FROM php:8.3.4-fpm-alpine3.19
 
-# Timezone
-ENV TZ=Europe/Moscow
+# Labels
+LABEL creatorName="Vagner dos Santos Cardoso"
+LABEL creatorEmail="vagnercardosoweb@gmail.com"
+
+# Set timezone
+ENV TZ=${TZ:-UTC}
 RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
 
-# Системные зависимости (только необходимое)
-RUN apk add --no-cache \
-    bash curl zip unzip tzdata \
-    icu-libs libpng libwebp libxslt libzip libxml2 oniguruma \
-    freetype libjpeg-turbo # для GD
+# Install non-dev dependencies
+RUN set -eux \
+  && apk add --no-cache \
+  git vim zip unzip bash curl tzdata icu-libs \
+  c-client make ca-certificates imap gmp gettext libssh2 yaml \
+  libintl libxslt libpng libwebp imap \
+  linux-headers oniguruma libxslt libpq vips \
+  gmp libzip libxml2 freetds
 
-# Установка зависимостей для сборки и PHP-расширений
-RUN apk add --no-cache --virtual .build-deps \
-    $PHPIZE_DEPS \
-    icu-dev \
-    libpng-dev \
-    libwebp-dev \
-    libxslt-dev \
-    libzip-dev \
-    libxml2-dev \
-    freetype-dev \
-    libjpeg-turbo-dev && \
-    # Настройка и установка GD
-    docker-php-ext-configure gd --with-jpeg --with-webp --with-freetype && \
-    # Установка основных расширений
-    docker-php-ext-install -j$(nproc) \
-        pdo_mysql \
-        mbstring \
-        xml \
-        zip \
-        intl \
-        bcmath \
-        sockets \
-        opcache \
-        gd && \
-    # Установка PECL расширений
-    pecl install redis apcu && \
-    # Включение PECL расширений (правильный синтаксис)
-    docker-php-ext-enable redis apcu && \
-    # Очистка
-    apk del .build-deps && \
-    rm -rf /tmp/pear
+# Install dependencies
+RUN set -eux \
+  && apk add --no-cache --virtual .build_deps \
+  libpng-dev libwebp-dev imap-dev \
+  linux-headers oniguruma-dev libxslt-dev postgresql-dev vips-dev \
+  libssh2-dev gmp-dev libzip-dev libxml2-dev freetds-dev yaml-dev \
+  $PHPIZE_DEPS
+  
+# Php extensions
+RUN set -eux \  
+  && docker-php-ext-install \
+  mysqli \
+  pdo_mysql \
+  pdo_pgsql \
+  pgsql\
+  bcmath \
+  mbstring \
+  xml \
+  exif \
+  zip \
+  soap \
+  intl \
+  xsl \
+  pcntl \
+  sockets \
+  sysvmsg \
+  sysvsem \
+  sysvshm \
+  imap \
+  gmp
+
+# additional supports
+
+# Install xdebug
+# RUN set -eux \
+  # && pecl install -o -f xdebug \
+  # && docker-php-ext-enable xdebug
+
+# Install YML
+RUN set -eux \
+  && pecl install -o -f yaml \
+  && docker-php-ext-enable yaml
+
+# Install redis
+RUN set -eux \
+  && pecl install -o -f redis \
+  && docker-php-ext-enable redis
+
+# Install mongodb
+# RUN set -eux \
+  # && pecl install -o -f mongodb \
+  # && docker-php-ext-enable mongodb 
+
+# Install apcu
+RUN set -eux \
+  && pecl install -o -f apcu \
+  && docker-php-ext-enable apcu
+
+# Install ssh2
+RUN set -eux \
+  && pecl install -o -f ssh2 \
+  && docker-php-ext-enable ssh2
+
+# Clean php extensions
+RUN set -eux \
+  && rm -rf /tmp/pear \
+  && docker-php-source delete
+
+# Clean up
+RUN set -eux \
+  && apk del --purge .build_deps \
+  && rm -rf /var/cache/apk/*
+
+# install opcache
+RUN set -eux \
+  opcache
+
+# GD with jpeg support
+RUN set -eux \  
+  && apk add --no-cache \  
+  zlib-dev \
+  libpng-dev \
+  libjpeg-turbo \
+  libjpeg-turbo-dev \
+  libwebp-dev \ 
+  freetype \ 
+  freetype-dev \   
+  && docker-php-ext-configure gd --with-jpeg --with-webp --with-freetype \
+  && docker-php-ext-install -j$(nproc) gd
 
 RUN set -eux \
-  && apk add --no-cache logrotate    
+  && apk add --no-cache logrotate
 
 # Install composer
 COPY --from=composer:2.7.2 /usr/bin/composer /usr/local/bin/composer
